dist: trusty
sudo: false
language: cpp
notifications:
  email: false

matrix:
  include:
    - env: CXX=g++
    - env: CXX=clang++
      addons { apt: {packages: ["clang"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty"] } }

script:
  - cd hello-world
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ./hello
