dist: trusty
sudo: required
language: cpp
notifications:
  email: false

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CXX=g++"

    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cd hello-world
  - mkdir build && cd build
  - CXX=${CXX} cmake ..
  - cmake --build .
